server {
  listen 80;
  server_tokens off;
  root /usr/share/nginx/html;
  location = /health { access_log off; return 200 'ok'; }
  location /api/auth { proxy_pass http://auth-service:5001; }
  location /api/products { proxy_pass http://catalog-service:5002; }
  location /api/categories { proxy_pass http://catalog-service:5002; }
  location /api/orders { proxy_pass http://orders-service:5003; }
  location / { try_files $uri $uri/ /index.html; }
}
