apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: 678419966897.dkr.ecr.us-east-1.amazonaws.com/devops-auth:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
        env:
        - name: SHARED_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: SHARED_SECRET
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5
