apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  namespace: marketly
spec:
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: ecr-pull
      containers:
        - name: orders-service
          image: marketly/orders-service:replace-me
          ports:
            - containerPort: 5003
          envFrom:
            - secretRef:
                name: app-secrets
            - configMapRef:
                name: app-config
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          resources:
            requests:
              cpu: 100m
              memory: 96Mi
            limits:
              cpu: 500m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /health
              port: 5003
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 5003
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5003
            periodSeconds: 10
